Enable CD for plugin release
jenkinsci/gatling-plugin pull request #23
Opened 2023-01-24 10:18 UTC by jonesbusy

Incrementalify plugin and enable CD

https://www.jenkins.io/doc/developer/publishing/releasing-cd/

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did

2023-01-24 10:51 UTC, NotMyFault requested changes

2023-01-24 10:51 UTC, NotMyFault commented on .mvn/maven.config
> +-Pmight-produce-incrementals
```suggestion
```
This is added twice.

2023-01-24 10:55 UTC, NotMyFault approved these changes

2023-03-17 09:48 UTC, merged

2023-03-17 09:49 UTC, slandelle commented
Thanks! Just sad that this is breaking the versioning scheme.